/**
 * Compliance disclaimer text constants.
 * Use these throughout signal/setup surfaces — never deviate.
 */

export const DISCLAIMERS = {
  SHORT:
    'For informational and educational use only. Not a guarantee of profit.',

  STANDARD:
    'Signals and trade setups are generated by rule-based models for informational and educational purposes only. They do not constitute financial advice, investment recommendations, or a guarantee of profit or investment outcome. Always conduct your own research and consult a qualified financial advisor before making investment decisions.',

  SIGNAL_CARD:
    'Model-driven insight. Not a buy/sell recommendation.',

  SETUP_CARD:
    'This trade setup is an educational output of a rule-based model. Entry, SL, and targets are indicative only. Past signal accuracy does not guarantee future results.',

  INTELLIGENCE_PAGE:
    'Quantorus365 Intelligence outputs are market intelligence tools, not guaranteed calls. All outputs are educational and informational in nature.',

  FOOTER:
    '© Quantorus365. All intelligence outputs are for informational use only and do not constitute financial advice. Investments in securities are subject to market risk.',

  OPTION_INTEL:
    'Option chain analysis is derived from public data and is indicative only. OI-based levels are not confirmed support/resistance zones.',
};

// Words to avoid in signal descriptions (compliance)
export const BANNED_PHRASES = [
  'guaranteed profit',
  'assured return',
  'confirmed profit',
  'sure shot',
  '100%',
  'risk free',
  'no loss',
];
