// ═══════════════════════════════════════════════════════════════════
//  Quantorus365 Stock Dashboard — Helper Functions
// ═══════════════════════════════════════════════════════════════════

import type { CandleBar } from './types';

/** Percentage position within 52-week range */
export function pct52w(low: number, high: number, ltp: number): number {
  if (high <= low || !ltp) return 0;
  return Math.round(((ltp - low) / (high - low)) * 100);
}

/** Confidence level band */
export function confLevel(c: number): 'high' | 'medium' | 'low' {
  return c >= 70 ? 'high' : c >= 50 ? 'medium' : 'low';
}

/** Color for return values */
export function returnColor(v: number): string {
  return v > 0 ? '#16A34A' : v < 0 ? '#DC2626' : '#64748B';
}

/** Compute approximate return from candle data */
export function calcReturn(candles: CandleBar[], ltp: number, nBars: number): number | null {
  if (!candles.length || !ltp) return null;
  const oldest = candles.slice(-Math.min(nBars, candles.length))[0];
  if (!oldest?.open) return null;
  return ((ltp - oldest.open) / oldest.open) * 100;
}

/** Determine signal reason sentiment */
export function reasonSentiment(text: string): 'positive' | 'negative' | 'neutral' {
  const t = text.toLowerCase();
  if (t.includes('above') || t.includes('bullish') || t.includes('strong') || t.includes('high'))
    return 'positive';
  if (t.includes('below') || t.includes('bearish') || t.includes('weak') || t.includes('low'))
    return 'negative';
  return 'neutral';
}

/** Check if NSE market is currently open (IST 9:15 - 15:30, Mon-Fri) */
export function isMarketOpen(): boolean {
  const now = new Date();
  const day = now.getUTCDay();
  if (day === 0 || day === 6) return false;
  const istMs = now.getTime() + (5.5 * 60 * 60 * 1000);
  const ist = new Date(istMs);
  const mins = ist.getUTCHours() * 60 + ist.getUTCMinutes();
  return mins >= 555 && mins <= 930; // 9:15 to 15:30
}

/** Generate trade plan text for clipboard */
export function buildTradePlanText(data: {
  symbol: string;
  signal_type: string | null;
  confidence: number | null;
  entry_price: number | null;
  stop_loss: number | null;
  target1: number | null;
  target2: number | null;
  risk_reward: number | null;
  score: number | null;
}): string {
  const lines = [
    `${data.symbol} — ${data.signal_type ?? 'NO SIGNAL'}`,
    `Confidence: ${data.confidence ?? '—'}%`,
    `Entry: ${data.entry_price ?? '—'}`,
    `Stop Loss: ${data.stop_loss ?? '—'}`,
    `Target 1: ${data.target1 ?? '—'}`,
    `Target 2: ${data.target2 ?? '—'}`,
    `R:R — 1:${data.risk_reward ?? '—'}`,
    `Q365 Score: ${data.score?.toFixed(1) ?? '—'}`,
    '',
    'Generated by Quantorus365',
  ];
  return lines.join('\n');
}
