'use client';

import { TrendingUp, TrendingDown, Activity, Clock, Zap } from 'lucide-react';
import { fmt, clsx }          from '@/lib/utils';
import { confLevel, reasonSentiment } from '../helpers';
import type { StockData }     from '../types';
import s from '../StockDashboard.module.scss';

interface Props { data: StockData; }

export default function SignalsTab({ data }: Props) {
  const dir  = data.signal_type ?? 'HOLD';
  const conf = data.confidence ?? 0;

  if (!data.signal_type) {
    return (
      <div className={s.panel}>
        <div className={s.empty}>
          <div className={s.emptyIcon}><Zap size={22} /></div>
          <div className={s.emptyTitle}>No active signal</div>
          <div className={s.emptyDesc}>
            Signal generates after the engine processes this symbol.
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className={s.panel}>
      <div className={clsx(s.signalCard, s['signalCard--live'])}>
        {/* Header */}
        <div className={s.signalHeader}>
          <span className={clsx(s.signalVerdict, s[`signalVerdict--${dir}`])}>
            {dir === 'BUY' ? <TrendingUp size={16} /> : dir === 'SELL' ? <TrendingDown size={16} /> : <Activity size={16} />}
            {dir}
          </span>
          <div className={s.signalConf}>
            <div className={s.signalConfValue}>{conf}%</div>
            <div className={s.signalConfCaption}>Confidence &middot; {data.signal_strength}</div>
          </div>
        </div>

        {/* Confidence bar */}
        <div className={s.confBar}>
          <div
            className={clsx(s.confBarFill, s[`confBarFill--${confLevel(conf)}`])}
            style={{ width: `${conf}%` }}
          />
        </div>

        {/* Price levels */}
        <div className={s.levelsGrid}>
          {([
            ['Entry',     data.entry_price, 'entry'],
            ['Stop Loss', data.stop_loss,   'stop'],
            ['Target 1',  data.target1,     'target'],
            ['Target 2',  data.target2,     'target'],
          ] as [string, number | null, string][]).map(([label, val, mod]) => (
            <div key={label} className={s.levelBox}>
              <div className={s.levelBoxLabel}>{label}</div>
              <div className={clsx(s.levelBoxValue, s[`levelBoxValue--${mod}`])}>
                {val != null ? fmt.currency(val) : '-'}
              </div>
            </div>
          ))}
        </div>

        {data.risk_reward != null && (
          <div style={{ fontSize: 13, color: '#64748B', textAlign: 'center', marginBottom: 12 }}>
            Risk / Reward: <strong style={{ color: '#0B1120' }}>1:{data.risk_reward}</strong>
          </div>
        )}

        {/* Reasons */}
        {data.reasons.length > 0 && (
          <>
            <div style={{ fontSize: 12, fontWeight: 700, color: '#334155', marginBottom: 6, marginTop: 8 }}>
              Signal Rationale
            </div>
            <div className={s.reasons}>
              {data.reasons.map((r, i) => {
                const sent = reasonSentiment(r.text);
                return (
                  <div key={i} className={s.reasonRow}>
                    <div className={clsx(s.reasonDot, s[`reasonDot--${sent}`])} />
                    <span className={s.reasonText}>{r.text}</span>
                    {r.factor_key && <span className={s.reasonKey}>{r.factor_key}</span>}
                  </div>
                );
              })}
            </div>
          </>
        )}

        {/* Freshness */}
        {data.signal_age_min != null && (
          <div className={s.freshness}>
            <Clock size={11} />
            <span>Generated {data.signal_age_min}m ago</span>
            <span style={{ color: '#CBD5E1' }}>|</span>
            <span>{data.data_source}</span>
          </div>
        )}
      </div>

      <div className={s.disclaimer}>
        This signal is generated by Quantorus365's rule-based algorithm using public market data. It does not constitute financial advice.
      </div>
    </div>
  );
}
